kitty_mod ctrl+shift

# Fonts
font_family      Fira Code Nerd Font
italic_font	   auto
bold_font   	   auto
bold_italic_font auto

# Font size (in pts)
font_size 	   12.0
adjust_line_height 1

# The amount the font size changes by (in pts) when
# increasing/decreasing the size in a terminal
font_size_delta  2

cursor_shape block

# Mouse
url_color #328da8
url_style curly
open_url_modifiers kitty_mod
open_url_with default

strip_trailing_spaces smart
rectangle_select_modifiers ctrl+alt
terminal_select_modifiers shift

# Tuning
# Turn this off if noticing input lag
sync_to_monitor yes

# Tab Bar
tab_bar_edge bottom
tab_bar_style powerline

# Turn off audio bells
enable_audio_bell no
visual_bell_duration 0.0

# Terminal Mappings and Config
map alt+t new_tab
map alt+w close_window
map alt+q close_terminal

# Go To Tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10

map ctrl+shift+g scroll_home
map ctrl+shift+G scroll_end
map ctrl+shift+h show_scrollback
map ctrl+shift+k scroll_line_up
map ctrl+shift+j scroll_line_down
map f1 launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay less +G -R

# Apprentice theme
# https://github.com/dexpota/kitty-themes/blob/master/themes/Apprentice.conf
cursor     #c7c7c7
cursor_text_color #feffff
selection_foreground #3e3e3e
selection_background #c1ddff
foreground #c8c8c8
background #323232
color0     #252525
color8     #555555
color1     #be7472
color9     #ff9900
color2     #709772
color10    #97bb98
color3     #989772
color11    #fefdbc
color4     #7199bc
color12    #9fbdde
color5     #727399
color13    #989abc
color6     #719899
color14    #6fbbbc
color7     #7f7f7f
color15    #feffff

