kitty_mod ctrl+shift

# Fonts
# {
  font_family 	   Hack Nerd Font
  italic_font	   auto
  bold_font   	   auto
  bold_italic_font auto

  # Font size (in pts)
  font_size 	   12.5
  adjust_line_height 1

  # The amount the font size changes by (in pts) when
  # increasing/decreasing the size in a terminal
  font_size_delta  2
# }

# Color scheme
# {
 background            #3f3f3f
 foreground            #dcdccc
 cursor                #73635a
 selection_background  #21322f
 color0                #4d4d4d
 color8                #709080
 color1                #705050
 color9                #dca3a3
 color2                #60b48a
 color10               #c3bf9f
 color3                #f0deae
 color11               #dfcf9f
 color4                #506070
 color12               #94bff3
 color5                #dc8cc3
 color13               #ec93d3
 color6                #8cd0d3
 color14               #93e0e3
 color7                #dcdccc
 color15               #ffffff
 selection_foreground  #3f3f3f
# }
# }

# Cursor
# {
  # Cursor colour
  cursor #d6d5c8

  # Shape of cursor (block, beam, underline)
  cursor_shape block
# }

# Turn off audio bells
enable_audio_bell no
visual_bell_duration 0.0

# Terminal Mappings and Config
# {

map alt+t new_tab
map alt+w close_window
map alt+q close_terminal

# Go To Tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10

# Clear Screen/Reset
# map ctrl+; clear_terminal reset active
# }
