kitty_mod ctrl+shift

# Fonts
# {
  font_family 	   Monospace
  italic_font	   auto
  bold_font   	   auto
  bold_italic_font auto

  # Font size (in pts)
  font_size 	   16.0

  # The amount the font size changes by (in pts) when
  # increasing/decreasing the size in a terminal
  font_size_delta  2
# }

# Color scheme
# {
  # background #35373a
  foreground #7148a0
  background #2b2c2d
# }

# Cursor
# {
  # Cursor colour
  cursor #d6d5c8

  # Shape of cursor (block, beam, underline)
  cursor_shape block
# }

# Turn off audio bells
enable_audio_bell no
visual_bell_duration 0.0

# Terminal Mappings and Config
# {

map alt+t new_tab
map alt+w close_window
map alt+q close_terminal

# Go To Tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10

# Clear Screen/Reset
map alt+backspace clear_terminal reset active
# }
