#! /bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
# picom -b

# bspc monitor -d I
# bspc monitor monitor DP-4 -d I II III IV V
# bspc monitor monitor HDMI-0 -d VI VII VIII IX X
xrandr --output HDMI-0 --off --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --mode 3840x1600 --pos 1080x0 --rotate normal --output DP-5 --off

bspc monitor -d I II III IV V VI VII VIII IX X
# Multi monitor only
#
# start_from=1
# monitors_connected=$(bspc query -M | wc -l)
# per_monitor=$(( 10 / monitors_connected ))
# for monitor in $(bspc query -M); do
#     bspc monitor $monitor -d $(seq $start_from $(( start_from + per_monitor - 1)))
#     start_from=$(( start_from + per_monitor ))
# done

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc monitor -d I II III IV V VI VII VIII IX X

source ~/.fehbg
redshift-gtk -O 5000

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
